set-option -g default-shell /bin/zsh

# Set a Ctrl-b shortcut for reloading your tmux config
bind r source-file ~/.tmux.conf

# Rename your terminals
set -g set-titles on
set -g set-titles-string '#(whoami)::#h::#(curl ipecho.net/plain;echo)'

# Allow control key to move forward word
set-window-option -g xterm-keys on

# Status bar customization
set -g status-bg colour236
#set -g status-fg white
#set -g status-interval 5
#set -g status-left-length 90
#set -g status-right-length 60
set -g status-justify right
set -g status-right '#[fg=Cyan]#S #[fg=white]%a %d %b %R' 
#set -g mouse on
#set -g mouse-resize-window on
#set -g mouse-resize-pane on

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*col*:Tc"


# Remap window navigation to vim
unbind-key j
bind-key j select-pane -D
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key l
bind-key l select-pane -R 

# Copy paste
bind P paste-buffer
# bind-key -t vi-copy 'v' begin-selection
# bind-key -t vi-copy 'y' copy-selection
# bind-key -t vi-copy 'r' rectangle-toggle
# bind-key -Tcopy-mode-vi v send -X begin-selection


#Fix arrow issue
unbind M-Left
unbind M-Right


#Find
bind-key / copy-mode \; send-key ?

#set -g default-command "reattach-to-user-namespace -l /bin/zsh"

set -g default-shell $SHELL 
#set -g default-command "reattach-to-user-namespace -l ${SHELL}"

# Theme
set -g @themepack 'powerline/double/blue'

# Disable status bar
set -g status on 


#Plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-yank'

set-option -g mouse on


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

