#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Customize to your needs...
# added by miniconda2 installer
# export PATH="$HOME/miniconda2/bin:$PATH"
source /Users/vmasrani/miniconda2/etc/profile.d/conda.sh
conda activate base
conda activate ml3


#Set PYTHONPATH
export PYTHONPATH=/Users/vmasrani/.python:$PYTHONPATH


#Init fasd
eval "$(fasd --init auto)"
alias v='f -e vim'

# Customize to your needs...
DIRSTACKSIZE=20

# Use i to get out of vim mode (enter vimmode with C-x C-v)
#bindkey '^[' vi-cmd-mode

EDITOR=vim
VISUAL=vim

## Antigen
source /usr/local/share/antigen/antigen.zsh
antigen bundle andrewferrier/fzf-z
antigen apply

## FZF-Z
export FZFZ_SUBDIR_LIMIT="500"
#export FZFZ_EXTRA_DIRS="'~/dev/phd' '~/Downloads' '~/Documents'"
export FZFZ_EXCLUDE_PATTERN='\.git|venv'

#Fix illegal bytestream error

#ls alias'#
alias l='ls -FGlAhp'                        # Preferred 'ls' implementation
alias lt='ls -qaltrh'                       # LS sorted chronologically
alias lf='ls -lShr'                         # LS sorted by file size
alias lr='ls -dl .*/ */'                    # LS only directories

#cd alias'#
alias cd..='cd ../'                         # Go back 1 directory level (for fast typers)
alias ..='cd ../'                           # Go back 1 directory level
alias .1='cd ../'                           # Go back 1 directory level
alias .2='cd ../../'                        # Go back 2 directory levels
alias .3='cd ../../../'                     # Go back 3 directory levels
alias .4='cd ../../../../'                  # Go back 4 directory levels
alias .5='cd ../../../../../'               # Go back 5 directory levels
alias .6='cd ../../../../../../'            # Go back 6 directory levels
alias .7='cd ../../../../../../../'            # Go back 6 directory levels
cdd() { builtin cd "$@"; ll; }               # Always list directory contents upon 'cd'

#tree alias's"
alias t='tree'
alias t2='tree -L 2'
alias t3='tree -L 3'
alias t4='tree -L 4'

#Allow group rename
autoload -U zmv
alias mmv='noglob zmv -W'

#Numeric sort
setopt numeric_glob_sort

#Preferred implementations
alias mv='mv -iv'                           # Preferred 'mv' implementation
alias mkdir='mkdir -pv'                     # Preferred 'mkdir' implementation
alias ll='ls -FGlAhp'                       # Preferred 'ls' implementation
alias less='less -FSRXc'                    # Preferred 'less' implementation
alias rm='rm -v'                            # Show what has been removed
alias cp='cp -v'                            # Show what has been copied
alias fr='open -a Finder ./'                # fr:            Opens current directory in MacOS Finder
alias ~="cd ~"                              # ~:            Go Home
alias h="history"                           # h:            History
alias path='echo -e ${PATH//:/\\n}'         # path:         Echo all executable Paths
alias show_options='shopt'                  # Show_options: display bash options settings
alias fix_stty='stty sane'                  # fix_stty:     Restore terminal settings when screwed up
alias cic='set completion-ignore-case On'   # cic:          Make tab-completion case-insensitive
alias du='du -sh'                           # Show usage in human readable format and sum content of subdirectories

#ssh aliases
alias ubc='ssh -Y vadmas@people.cs.ubc.ca'
alias cluster="ssh -A -t vadmas@remote.cs.ubc.ca ssh headnode"
alias cedar="ssh vadmas@cedar.computecanada.ca"
alias neuro="ssh vadmas@neuromancer.cs.ubc.ca"

# pullubc (){
#     if [ "$1" = "-r" ]; then
#      scp -r vadmas@people.cs.ubc.ca:$2 $3;
#     else
#      scp vadmas@people.cs.ubc.ca:$1 $2;
#     fi
# }

# pushubc (){
#   if [ "$1" = "-r" ]; then
#     scp -r $2 vadmas@people.cs.ubc.ca:/ubc/cs/home/v/vadmas/scp;
#     else
#     scp $1 vadmas@people.cs.ubc.ca:/ubc/cs/home/v/vadmas/scp;
#     fi
# }

#Function that pronounces words - calls the "pronounce" script in ~/bin
alias say='pronounce'

mk () { mkdir -p "$1" && cd "$1"; }         # mk:          Makes new Dir and jumps inside
trash () { command mv "$@" ~/.Trash ; }     # trash:        Moves a file to the MacOS trash
ql () { qlmanage -p "$*" >& /dev/null; }    # ql:           Opens any file in MacOS Quicklook Preview
alias DT='tee ~/Desktop/terminalOut.txt'    # DT:           Pipe content to file on MacOS Desktop
alias zshrc='vim ~/.zshrc'



# #   extract:  Extract most know archives with one command
# #   ---------------------------------------------------------
    extract () {
        if [ -f $1 ] ; then
            case $1 in
                *.tar.bz2)   tar xjf $1     ;;
        *.tar.gz)    tar xzf $1     ;;
        *.bz2)       bunzip2 $1     ;;
        *.rar)       unrar e $1     ;;
        *.gz)        gunzip $1      ;;
        *.tar)       tar xf $1      ;;
        *.tbz2)      tar xjf $1     ;;
        *.tgz)       tar xzf $1     ;;
        *.zip)       unzip $1       ;;
        *.Z)         uncompress $1  ;;
        *.7z)        7z x $1        ;;
        *)     echo "'$1' cannot be extracted via extract()" ;;
        esac
        else
            echo "'$1' is not a valid file"
                fi
    }

#In order to paste commands that start with a '$'
function $ { "$@"  }

#function dict {open dict:://$1}

#   spotlight: Search for a file using MacOS Spotlight's metadata
#   -----------------------------------------------------------
    spotlight () { mdfind "kMDItemDisplayName == '$@'wc"; }

#youtube audio downloader

function youtube {
if [ "$1" = "-d" ]; then
   cd ~/Downloads/youtube
else
   youtube-dl  --extract-audio --prefer-ffmpeg --audio-format mp3 -o "~/Downloads/youtube/%(title)s.%(ext)s" $1
fi
}

function youtube_pl {
youtube-dl --extract-audio --prefer-ffmpeg --audio-format mp3 -o "~/Downloads/youtube/%(title)s.%(ext)s" --playlist-start $2 $1;
}

function getlec {
  dir="/Users/vmasrani/Dropbox/lectures";
  title=$(youtube-dl -e $1)
  youtube-dl --extract-audio --prefer-ffmpeg --audio-format mp3 -o "$dir/%(title)s.%(ext)s" $1 && id3tag --artist=Lectures --album=Lectures $dir/$title.mp3;
}

function getzip {
curl $1 > package.zip;
extract package.zip;
rm package.zip;
}

#Append to end of file. Made function because one arrow (>) clears file which is dangerous
function append(){echo $1  >> $2 }


#Send attachment without message or subject
# send file.pdf vadmas@gmail.com
function send(){echo "" | mutt -s "Attachment" $2 -a $1}

#mysql
alias mysql_start='sudo /usr/local/mysql/support-files/mysql.server start'
alias mysql_stop='sudo /usr/local/mysql/support-files/mysql.server stop'
alias mysql_shell='mysql -u root -p -h localhost'
#So mysql can communicate with python
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/

# Fix python bytecode
export PYTHONDONTWRITEBYTECODE=1

#Ruby
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

#git
#Get only tarball with no git repo info
function targit(){
curl -L $(sed 's%\.git%\/tarball\/master%' <<<"$1") | tar zx
}
#fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd -t f . $HOME"

# Use fd to generate the list for directory completion
#_fzf_compgen_dir() {
#  fd --type d --hidden --follow --exclude ".git" . "$1"
#}
#_fzf_compgen_path() {
#  fd --hidden --follow --exclude ".git" . "$1"
#}

# -------------
# GIT heart FZF
# -------------

is_in_git_repo() {
  git rev-parse HEAD > /dev/null 2>&1 || echo "This_is_not_a_git_repository"
}

fzf-down() {
  fzf --height 50% "$@" --border
}

FZF_PREFIX="fg-"

function "${FZF_PREFIX}ga" () {
  is_in_git_repo || return
  git -c color.status=always status --short |
  fzf-down -m --ansi --nth 2..,.. \
    --preview '(git diff --color=always -- {-1} | sed 1,4d; cat {-1}) | head -500' |
  cut -c4- | sed 's/.* -> //'
}

function "${FZF_PREFIX}gb" () {
  is_in_git_repo || return
  git branch -a --color=always | grep -v '/HEAD\s' | sort |
  fzf-down --ansi --multi --tac --preview-window right:70% \
    --preview 'git log --oneline --graph --date=short --pretty="format:%C(auto)%cd %h%d %s" $(sed s/^..// <<< {} | cut -d" " -f1) | head -'$LINES |
  sed 's/^..//' | cut -d' ' -f1 |
  sed 's#^remotes/##'
}

# git tag
function "${FZF_PREFIX}gt" () {
  is_in_git_repo || return
  git tag --sort -version:refname |
  fzf-down --multi --preview-window right:70% \
    --preview 'git show --color=always {} | head -'$LINES
}

function "${FZF_PREFIX}gh" () {
  is_in_git_repo || return
  git log --date=short --format="%C(green)%C(bold)%cd %C(auto)%h%d %s (%an)" --graph --color=always |
  fzf-down --ansi --no-sort --reverse --multi --bind 'ctrl-s:toggle-sort' \
    --header 'Press CTRL-S to toggle sort' \
    --preview 'grep -o "[a-f0-9]\{7,\}" <<< {} | xargs git show --color=always | head -'$LINES |
  grep -o "[a-f0-9]\{7,\}"
}

function "${FZF_PREFIX}gr" () {
  is_in_git_repo || return
  git remote -v | awk '{print $1 "\t" $2}' | uniq |
  fzf-down --tac \
    --preview 'git log --oneline --graph --date=short --pretty="format:%C(auto)%cd %h%d %s" {1} | head -200' |
  cut -d$'\t' -f1
}

# join-lines() {
#   local item
#   while read item; do
#     echo -n "${(q)item} "
#   done
# }
#
# bind-git-helper() {
#   local char
#   for c in $@; do
#     eval "fzf-g$c-widget() { local result=\$(${FZF_PREFIX}g$c | join-lines); zle reset-prompt; LBUFFER+=\$result }"
#     eval "zle -N fzf-g$c-widget"
#     eval "bindkey '^h^$c' fzf-g$c-widget"
#   done
# }
# bind-git-helper f b t r h
# unset -f bind-git-helper

# fshow - git commit browser
fshow() {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
  fzf --ansi --no-sort --reverse --tiebreak=index --bind=ctrl-s:toggle-sort \
      --bind "ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
                {}
FZF-EOF"
}

# # stage files multi-selected modified files
ga() {
   git add $("${FZF_PREFIX}ga")
 }

gdiff() {
   git diff $("${FZF_PREFIX}ga")
}

#
#command line dictionary
alias def='sdcv'

#compile and open latex
function pt(){
pdflatex $1.tex && open $1.pdf
}

### LESS Syntax Highlight ###
## Enable syntax-highlighting in less.
## brew install source-highlight
## First, add these two lines to ~/.bashrc
export LESSOPEN="| /usr/local/bin/src-hilite-lesspipe.sh %s"
export LESS=" -R "
alias less='less -M -X -g -i -J --underline-special --SILENT'
#alias cat="highlight $1 --out-format xterm256 --quiet --force --style solarized-dark"
#alias ccat="highlight $1 --out-format xterm256 --line-numbers --quiet --force --style solarized-dark"

# define function that retrieves and runs last command
function run-again {
    # get previous history item
    zle up-history
    # confirm command
    zle accept-line
}

# define run-again widget from function of the same name
zle -N run-again

# bind widget to Ctrl+X in viins mode
bindkey '^X' run-again

# java
export JAVA_HOME=$(/usr/libexec/java_home)

# Config
alias config='/usr/bin/git --git-dir=$HOME/.myconf/ --work-tree=$HOME'

### Better vim mode

# Better searching in command mode
bindkey -M vicmd '?' history-incremental-search-backward
bindkey -M vicmd '/' history-incremental-search-forward

# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export KEYTIMEOUT=1

# Enable Ctrl-x-e to edit command line
autoload -U edit-command-line

# Emacs style
zle -N edit-command-line
bindkey '^f' edit-command-line

#
task list


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/vmasrani/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/vmasrani/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/vmasrani/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/vmasrani/google-cloud-sdk/completion.zsh.inc'; fi

